<template>
  <div style="heigth: 100vh;">
    <div class="md-layout">
      <div class="md-layout-item md-size-100" style="padding:0;">
        <clientesLarge :text="text" class="large"></clientesLarge>
        <clientesMedium :text="text" class="medium"></clientesMedium>
      </div>
    </div>
  </div>
</template>

<script>
import { AnimatedNumber } from "@/components";
import clientesLarge from "../subcomponents/clientes/clientes_large.vue";
import clientesMedium from "../subcomponents/clientes/clientes_medium.vue";
export default {
  data() {
    return {
      text: {
        title: "Clientes",
        mapCount: [
          {
            text: "Países",
            number: "4"
          },
          {
            text: "Clientes",
            number: "250"
          },
          {
            text: "Usuarios",
            number: "2000"
          }
        ],
        carrousel: {
          title: "Nuestros clientes nos definen",
          body: "Somos el software de la industria creativa.",
          items: [
            {
              text:
                "Unabase nos ha ayudado a ordenar y manejar un gran número de proyectos en simultáneo, logrando tener claro las rentabilidades de cada uno. Además, nos permite cerrarlos y evaluar su rendimiento",
              autor: "Felipe Díaz - Modo Santiago"
            },
            {
              text:
                "En La Casa Films y Oriental Films, trabajamos hace 10 años con Unabase. En general, estoy buena parte de mi tiempo fuera del país y unabase funciona en perfectas condiciones en forma remota. Además, en caso de necesitarlos, su ayuda es inmediata y efectiva.",
              autor: "Leopoldo Luisetti. - La Casa Films"
            },
            {
              text:
                "Unabase nos ha ayudado a generar mecanismos de normalización de precios y costos. Permitiendo modernizar y transparentar la comunicación comercial con nuestros clientes",
              autor: "Andres Paucay - Shangri La"
            },
            {
              text:
                "Unabase es un software muy intuitivo y de fácil uso que permite mantener un orden, eficiencia y claridad de los negocios desde el ámbito contable hasta el detalle de cada línea de trabajo. Además, cuenta con soporte online rápido y efectivo",
              autor: "Mariano Fernández - Ludika"
            },
            {
              text:
                "Unabase nos ayuda a manejar nuestros presupuestos y costos de manera muy efectiva y certera. Los mecanismos de control de presupuestos y facilidad para generar y controlar gastos nos ayuda mucho en el manejo diario.",
              autor: "Cristian Urzua - Grupo Sud"
            }
          ]
        }
      }
    };
  },
  components: {
    AnimatedNumber,
    clientesLarge,
    clientesMedium
  },
  methods: {},
  created() {},
  mounted() {}
};
</script>


<style lang="scss">
/* ANIMACION DE ENTRADA DE SWITCH (BARRA) */

.fade-in-fwd {
  -webkit-animation: fade-in-fwd 2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: fade-in-fwd 2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-11-25 18:17:38
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-fwd
 * ----------------------------------------
 */
@-webkit-keyframes fade-in-fwd {
  0% {
    -webkit-transform: translateZ(-80px);
    transform: translateZ(-80px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}
@keyframes fade-in-fwd {
  0% {
    -webkit-transform: translateZ(-80px);
    transform: translateZ(-80px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}

/* ANIMACION DE ENTRADA DE SWITCH (BOLITA) */

.slide-in-left {
  -webkit-animation: slide-in-left 1s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: slide-in-left 1s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

.slide-in-left2 {
  -webkit-animation: slide-in-left 2s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: slide-in-left 2s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

.slide-in-left3 {
  -webkit-animation: slide-in-left 3s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: slide-in-left 3s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

.slide-in-left4 {
  -webkit-animation: slide-in-left 4s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: slide-in-left 4s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

.slide-in-left5 {
  -webkit-animation: slide-in-left 5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: slide-in-left 5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-11-25 18:19:23
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}

.usersCarousel {
  margin-top: -7%;
}

@media (max-width: 992px) {
  .switchClientes {
    display: none !important;
  }
  .mapImg {
    display: none !important;
  }

  .clientsCount {
    display: none !important;
  }

  .usersCarousel {
    .v-carousel {
      height: 40% !important;
    }
    margin-top: 0 !important;
  }
}

/* DESKTOP  */
.medium {
  display: none !important;
}

@media (max-width: 1904px) {
  .medium {
    display: block !important;
  }
}

/* 4K ULTRA-WIDES  */
.large {
  display: none !important;
}

@media (min-width: 1904px) {
  .large {
    display: block !important;
  }
}
</style>