<template>
  <div style="heigth: 100vh; margin-top: 10%;">
    <div class="md-layout">
      <div class="md-layout-item md-size-33 md-small-size-100 slide-in-bottom-3">
        <v-card
          class="mx-auto fade-in"
          max-width="344"
          style="margin-top: 25%; box-shadow: none; z-index:1000 !important;"
        >
          <v-card-text>
            <v-spacer></v-spacer>
            <span class="display-1 text--primary pull-right">
              <b>Contacto</b>
            </span>
            <br />
            <br />
            <br />

            <span class="subheading">Hablemos y conoce nuestra soluciòn!</span>

            <br />
            <br />
            <div class="display-1 pull-right">Chile</div>
            <br />
            <br />
            <div class="subtitle-1 pull-right">+56 9 4810 6304 / +56 9 4810 6304</div>

            <br />
            <br />
            <div class="display-1 pull-right">Perú</div>
            <br />
            <br />
            <div class="subtitle-2 pull-right">+51 9 4810 6304</div>

            <br />
            <br />
            <div class="subheading font-weight-bold pull-right">
              <b>ventas@unabase.com</b>
            </div>
          </v-card-text>
          <v-card-actions style="z-index:1000 !important;"></v-card-actions>
        </v-card>
      </div>

      <div class="md-layout-item md-size-33 md-small-size-100 slide-in-bottom-1">
        <md-empty-state
          style="margin-top: 25% !important;"
          class="md-success"
          md-icon="format_list_numbered"
          md-label="Seccion # 6"
          md-description="CONTACTO"
        ></md-empty-state>
      </div>

      <div class="md-layout-item md-size-33 md-small-size-100 slide-in-bottom-2">
        <md-empty-state
          style="margin-top: 25% !important;"
          class="md-success"
          md-icon="format_list_numbered"
          md-label="Seccion # 6"
          md-description="CONTACTO"
        ></md-empty-state>
      </div>
    </div>
  </div>
</template>


<script>
export default {
  data() {
    return {};
  },
  components: {},
  methods: {},
  created() {},
  mounted() {}
};
</script>

<style>
/* ANIMACIONES DE ENTRADA */

.slide-in-bottom-1 {
  -webkit-animation: slide-in-bottom 3s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: slide-in-bottom 3s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

.slide-in-bottom-2 {
  -webkit-animation: slide-in-bottom 4s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: slide-in-bottom 4s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}
.slide-in-bottom-3 {
  -webkit-animation: slide-in-bottom 2s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: slide-in-bottom 2s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-11-3 21:21:11
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-bottom
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(1000px);
    transform: translateY(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(1000px);
    transform: translateY(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
</style>